[package]
name = "rpc"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2021"

[dependencies]
rd-interface = { path = "../../rd-interface/", version = "0.4" }
rd-std = { path = "../../rd-std/", version = "0.1" }
# rd-interface = "0.3"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.26"
tokio = { version = "1.5.0", features = ["rt"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
futures = "0.3"
parking_lot = "0.12.0"
serde_json = "1.0.78"
cbor4ii = { version = "0.3.1", features = ["serde1"] }
